### ISSUE TITLE
Не совсем верное Read.me

### ISSUE THREAD

**Issue by UmbrellaMalware** [Phinnik/slaves_api#6]
В процессе установки не обязательно входить в виртуальное окружение. В примере указан вход в окружение Windows, но если устанавливать окружение через Linux, у пользователя будет ошибка. 
Я предлагаю убрать вовсе эту секцию и оформить пакет в https://pypi.org/

**Comment by Phinnik** [comment]
Согласен, будет сделано в ближайшее время

**Comment by Phinnik** [comment]
Пакет оформлен не будет. Приложение закрыто и смысла засорять pypi нет.
